package vn.com.vti.job_site.entity;

public class BusinessType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.business_type.business_type_id
     *
     * @mbg.generated Mon Oct 28 23:54:25 JST 2024
     */
    private Integer businessTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.business_type.business_type_name
     *
     * @mbg.generated Mon Oct 28 23:54:25 JST 2024
     */
    private String businessTypeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.business_type.business_type_id
     *
     * @return the value of public.business_type.business_type_id
     *
     * @mbg.generated Mon Oct 28 23:54:25 JST 2024
     */
    public Integer getBusinessTypeId() {
        return businessTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.business_type.business_type_id
     *
     * @param businessTypeId the value for public.business_type.business_type_id
     *
     * @mbg.generated Mon Oct 28 23:54:25 JST 2024
     */
    public void setBusinessTypeId(Integer businessTypeId) {
        this.businessTypeId = businessTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.business_type.business_type_name
     *
     * @return the value of public.business_type.business_type_name
     *
     * @mbg.generated Mon Oct 28 23:54:25 JST 2024
     */
    public String getBusinessTypeName() {
        return businessTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.business_type.business_type_name
     *
     * @param businessTypeName the value for public.business_type.business_type_name
     *
     * @mbg.generated Mon Oct 28 23:54:25 JST 2024
     */
    public void setBusinessTypeName(String businessTypeName) {
        this.businessTypeName = businessTypeName;
    }
}