package vn.com.vti.job_site.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.job_site.entity.BusinessType;
import vn.com.vti.job_site.entity.BusinessTypeExample;

public interface BusinessTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.business_type
     *
     * @mbg.generated Mon Oct 28 23:54:25 JST 2024
     */
    long countByExample(BusinessTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.business_type
     *
     * @mbg.generated Mon Oct 28 23:54:25 JST 2024
     */
    int deleteByExample(BusinessTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.business_type
     *
     * @mbg.generated Mon Oct 28 23:54:25 JST 2024
     */
    int deleteByPrimaryKey(Integer businessTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.business_type
     *
     * @mbg.generated Mon Oct 28 23:54:25 JST 2024
     */
    int insert(BusinessType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.business_type
     *
     * @mbg.generated Mon Oct 28 23:54:25 JST 2024
     */
    int insertSelective(BusinessType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.business_type
     *
     * @mbg.generated Mon Oct 28 23:54:25 JST 2024
     */
    List<BusinessType> selectByExample(BusinessTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.business_type
     *
     * @mbg.generated Mon Oct 28 23:54:25 JST 2024
     */
    BusinessType selectByPrimaryKey(Integer businessTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.business_type
     *
     * @mbg.generated Mon Oct 28 23:54:25 JST 2024
     */
    int updateByExampleSelective(@Param("row") BusinessType row, @Param("example") BusinessTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.business_type
     *
     * @mbg.generated Mon Oct 28 23:54:25 JST 2024
     */
    int updateByExample(@Param("row") BusinessType row, @Param("example") BusinessTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.business_type
     *
     * @mbg.generated Mon Oct 28 23:54:25 JST 2024
     */
    int updateByPrimaryKeySelective(BusinessType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.business_type
     *
     * @mbg.generated Mon Oct 28 23:54:25 JST 2024
     */
    int updateByPrimaryKey(BusinessType row);
}