package vn.com.vti.job_site.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.job_site.entity.Company;
import vn.com.vti.job_site.entity.CompanyExample;

public interface CompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.company
     *
     * @mbg.generated Mon Oct 28 23:26:14 JST 2024
     */
    long countByExample(CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.company
     *
     * @mbg.generated Mon Oct 28 23:26:14 JST 2024
     */
    int deleteByExample(CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.company
     *
     * @mbg.generated Mon Oct 28 23:26:14 JST 2024
     */
    int deleteByPrimaryKey(Integer companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.company
     *
     * @mbg.generated Mon Oct 28 23:26:14 JST 2024
     */
    int insert(Company row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.company
     *
     * @mbg.generated Mon Oct 28 23:26:14 JST 2024
     */
    int insertSelective(Company row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.company
     *
     * @mbg.generated Mon Oct 28 23:26:14 JST 2024
     */
    List<Company> selectByExample(CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.company
     *
     * @mbg.generated Mon Oct 28 23:26:14 JST 2024
     */
    Company selectByPrimaryKey(Integer companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.company
     *
     * @mbg.generated Mon Oct 28 23:26:14 JST 2024
     */
    int updateByExampleSelective(@Param("row") Company row, @Param("example") CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.company
     *
     * @mbg.generated Mon Oct 28 23:26:14 JST 2024
     */
    int updateByExample(@Param("row") Company row, @Param("example") CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.company
     *
     * @mbg.generated Mon Oct 28 23:26:14 JST 2024
     */
    int updateByPrimaryKeySelective(Company row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.company
     *
     * @mbg.generated Mon Oct 28 23:26:14 JST 2024
     */
    int updateByPrimaryKey(Company row);
}